### ISSUE TITLE
Raw identifier in struct for start fn doesn't include `r#` in generated code

### ISSUE THREAD

**Issue by lazkindness** [elastio/bon#224] opened 2024-11-30 23:54 UTC
If you have a struct like the following:

```rust
#[derive(Builder)]
#[builder(start_fn = r#for)]
struct Sources {
    #[builder(start_fn)]
    r#for: i32,
    sources: Vec<String>,
}
```
The produced `start_fn` will be `Sources::for`, which doesn't actually build

### A note for the community from the maintainers

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to help the maintainers with prioritizing it. You may add a comment describing your real use case related to this issue for us to better understand the problem domain.

**Comment by Veetaha** [comment] 2024-12-01 16:37
>The produced `start_fn` will be `Sources::for`, which doesn't actually build

I've checked this locally with `bon` 3.1.1 and the generated code looks like this:

```rust
#[automatically_derived]
impl Sources {
    #[doc = "Create an instance of [`Sources`] using the builder syntax"]
    #[inline(always)]
    #[allow(clippy::inline_always, clippy::use_self, clippy::missing_const_for_fn)]
    #[allow(deprecated)]
    fn r#for(r#for: i32) -> SourcesBuilder {
        SourcesBuilder {
            __unsafe_private_phantom: ::core::marker::PhantomData,
            __unsafe_private_start_fn_args: (r#for,),
            __unsafe_private_named: ::core::default::Default::default(),
        }
    }
}
```

So the problem doesn't reproduce for me with the provided snippet of code. Maybe you are missing some other attributes that could lead to such bug?

**Comment by Veetaha** [comment] 2024-12-10 01:07
I'm closing this one, since it's not reproducible for me. My theory is that you could stumble on the problem, that`Source::for()` doesn't work, which is expected as it requires an `r#` prefix at the call site as well.

Feel free to reopen if I'm wrong here, and the problem exists, but is a bit different

**Closed by Veetaha** 2024-12-10 01:07 UTC
Labels: waiting on OP
